"""regen: create grade_reports (from current models)

Revision ID: 31ef04faea30
Revises: 0001_create_grade_reports_table
Create Date: 2025-09-03 16:17:15.906163

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "31ef04faea30"
down_revision: Union[str, Sequence[str], None] = "0001_create_grade_reports_table"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
